# Generated by Django 5.0.2 on 2025-12-26 08:07

import applications.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nom complet"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "position_applied",
                    models.CharField(max_length=200, verbose_name="Poste souhaité"),
                ),
                (
                    "years_experience",
                    models.IntegerField(default=0, verbose_name="Années d'expérience"),
                ),
                (
                    "availability_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de disponibilité"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, verbose_name="Message / Lettre de motivation"
                    ),
                ),
                (
                    "cv_file",
                    models.FileField(
                        help_text="Formats acceptés: PDF, DOC, DOCX. Taille max: 5MB",
                        upload_to=applications.models.cv_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx"]
                            )
                        ],
                        verbose_name="CV (PDF/DOC/DOCX)",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de candidature"
                    ),
                ),
                (
                    "reviewed",
                    models.BooleanField(default=False, verbose_name="Examiné"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
            ],
            options={
                "verbose_name": "Candidature",
                "verbose_name_plural": "Candidatures",
                "ordering": ["-applied_at"],
            },
        ),
    ]
