# Generated by Django 5.0.2 on 2025-12-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="availability_date",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="email",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="position_applied",
        ),
        migrations.RemoveField(
            model_name="jobapplication",
            name="years_experience",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="physical_address",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Adresse physique"
            ),
        ),
    ]
