# Generated by Django 5.0.2 on 2025-12-27 23:53

import applications.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_update_application_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="application_type",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Remplir manuellement"),
                    ("CV_UPLOAD", "Télécharger mon CV"),
                ],
                default="MANUAL",
                max_length=20,
                verbose_name="Type de candidature",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="education",
            field=models.TextField(
                blank=True,
                help_text="Exemple: Diplôme d'État en Sciences Commerciales et Gestion (2018-2021) - Institut X, Kinshasa",
                null=True,
                verbose_name="Études faites",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="how_heard_about",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AFFICHE", "Affiche"),
                    ("MOTEUR_RECHERCHE", "Moteur de recherche"),
                    ("PERSONNE", "A travers une personne"),
                ],
                max_length=20,
                verbose_name="Comment avez-vous connu Shine Congo?",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="how_heard_details",
            field=models.CharField(
                blank=True,
                help_text="Où avez-vous vu l'affiche / Quel moteur de recherche / Nom de la personne",
                max_length=300,
                null=True,
                verbose_name="Détails",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="languages",
            field=models.CharField(
                blank=True,
                help_text="Exemple: Français (courant), Lingala (maternelle), Anglais (notions)",
                max_length=200,
                null=True,
                verbose_name="Langues parlées",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="lieu_de_naissance",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="nationalite",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nationalité"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="nom",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="post_nom",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Post-nom"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="prenom",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Prénom"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="sexe",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculin"), ("F", "Féminin")],
                max_length=1,
                null=True,
                verbose_name="Sexe",
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="skills",
            field=models.TextField(
                blank=True,
                help_text="Exemple: Maîtrise de Microsoft Office, Bonne communication, Expérience en service client, Capacité à travailler en équipe",
                null=True,
                verbose_name="Compétences et profil",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ville"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="cv_file",
            field=models.FileField(
                blank=True,
                help_text="Formats acceptés: PDF, DOC, DOCX. Taille max: 5MB",
                null=True,
                upload_to=applications.models.cv_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "doc", "docx"]
                    )
                ],
                verbose_name="CV (PDF/DOC/DOCX)",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nom complet"
            ),
        ),
    ]
