# Generated by Django 5.0.2 on 2025-12-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre du poste"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(verbose_name="Description")),
                ("responsibilities", models.TextField(verbose_name="Responsabilités")),
                ("requirements", models.TextField(verbose_name="Exigences")),
                ("benefits", models.TextField(blank=True, verbose_name="Avantages")),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Temps plein"),
                            ("PART_TIME", "Temps partiel"),
                            ("CONTRACT", "Contrat"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                        verbose_name="Type d'emploi",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="Kinshasa, RDC", max_length=200, verbose_name="Lieu"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Poste",
                "verbose_name_plural": "Postes",
                "ordering": ["-created_at"],
            },
        ),
    ]
